apiVersion: v1
kind: Pod
metadata: 
  name: gitrepo-volume-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  initContainers:
  - name: git-cloner
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --
      - https://github.com/pwolf15/kubia-website-example.git
      - /data
    volumeMounts:
    - mountPath: /data
      name: html

  volumes:
  - name: html
    emptyDir: {}